name: 🚀 Deploy Code via SFTP

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  sftp-upload:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_SERVER_IP }} 
          username: ${{ secrets.SFTP_LOGIN }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server-dir: '/home/a0984460/domains/a0984460.xsph.ru/public_html/wp-content/themes/utopia'
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**