name: 🚀 Deploy Code via SFTP

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  sftp-upload:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_SERVER_IP }}
          username: ${{ secrets.SFTP_LOGIN }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server-dir: /public_html/utopia-orchestra.org/wp-content/themes/utopia/
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**

      # - name: 📂 SFTP uploader # Upload to SFTP
      #   uses: wangyucode/sftp-upload-action@v2.0.2
      #   with:
      #     host: ${{ secrets.SFTP_SERVER_IP }} # Recommended to put the credentials in github secrets.
      #     username: ${{ secrets.SFTP_LOGIN }}
      #     password: ${{ secrets.SFTP_PASSWORD }}
      #     compress: true # Compression
      #     forceUpload: false # Optional, Force uploading all files, Default to false(upload only newer files).
      #     localDir: '.' # Required, Absolute or relative to cwd.
      #     remoteDir: '/home/a0984460/domains/a0984460.xsph.ru/public_html/wp-content/themes/utopia/' # Required, Absolute path only.
      #     exclude: '.git/*,.DS_Store,node_modules/*,vendor/*'
