name: 🚀 Deploy Code via SFTP

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  sftp-upload:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: 📂  FTP Deployer
        uses: sand4rt/ftp-deployer@v1.8
        with:
          sftp: false # optional
          host: ${{ secrets.SFTP_SERVER_IP }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
          port: 21 # optional, default is: 21
          username: ${{ secrets.SFTP_LOGIN }} # FTP username
          password: ${{ secrets.SFTP_PASSWORD }} # FTP password
          remote_folder: '/home/a0984460/domains/a0984460.xsph.ru/public_html/wp-content/themes/utopia/' # optional, remote path of your FTP server
          local_folder:  # optional, local path, default is: dist
          cleanup: false # optional, remove existing files inside FTP remote folder
          include: '[]' # optional, e.g. '['dist']'
          exclude: |
            .git*
            .git*/**
            node_modules/**
            vendor/** 
          passive: true # optional